apiVersion: v1
kind: Service
metadata:
  name: nginx-personalizado-clusterip
spec:
  type: ClusterIP
  selector:
    app: nginx-personalizado
    ver: "3"
  ports:
    - targetPort: 80  # endpoint
      port: 8080      # clusterip
