apiVersion: v1
kind: Service
metadata:
  name: nginx-personalizado-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: nginx-personalizado
    ver: "3"
  ports:
    - targetPort: 80  # endpoint
      port: 80        # loadbalancer
  externalIPs:
    - 172.20.227.8  # nodo con IP pública
