apiVersion: v1
kind: Service
metadata:
  name: nginx-personalizado-nodeport
spec:
  type: NodePort
  selector:
    app: nginx-personalizado
    ver: "3"
  ports:
    - targetPort: 80  # endpoint
      port: 8080      # clusterip
      nodePort: 31000 # nodeport
